spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: shakti.singh@xcelore.com
        password: htim qfek psnb czpn
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
