spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: abc@gmail.com //write mail here 
        password: xxxx xxxx xxxx xxxx // write app password 
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
